apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
  namespace: wisecow-app
  labels:
    app: wisecow
spec:
  type: ClusterIP
  selector:
    app: wisecow
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4499
    name: http
  sessionAffinity: None
